import Foundation

/// Generates a reviewable `bash` script from `Finding.suggestion`s — the tool
/// never moves or renames anything itself. The script it produces is meant
/// to be opened in an editor, read line by line, and only then run by a
/// human; it starts with a blocking confirmation gate and never contains a
/// destructive command (`rm`, `rmdir`, `trash`, overwriting redirects).
///
/// Only `.sureError` findings are included by default. `.suspicious`
/// findings can be added via `includeSuspicious`, but their commands are
/// emitted fully commented out so nothing runs without a deliberate,
/// separate edit. `.probablyIntentional` findings are never included,
/// regardless of flags — the audit engine already decided those are
/// probably fine.
public enum SuggestionScript {
    /// Builds the script text, or `nil` if no finding produced any content
    /// (nothing with a non-nil suggestion at an included severity).
    ///
    /// `commentSuspicious` controls whether `.suspicious` findings' commands
    /// are emitted commented-out (the default, safe behavior for a general
    /// audit suggestion script) or fully active — the cleanup command passes
    /// `false` since its `.suspicious` "cleanup-candidate" findings are
    /// already reversible `mv`-into-quarantine moves, not something that
    /// needs a second manual uncomment step on top of the script's own
    /// blocking confirmation gate.
    public static func generate(
        findings: [Finding],
        root: URL,
        includeSuspicious: Bool = false,
        commentSuspicious: Bool = true
    ) -> String? {
        var blocks: [String] = []
        for finding in findings {
            guard finding.suggestion != nil else { continue }
            switch finding.severity {
            case .sureError:
                blocks.append(block(for: finding, root: root, commented: false))
            case .suspicious:
                guard includeSuspicious else { continue }
                blocks.append(block(for: finding, root: root, commented: commentSuspicious))
            case .probablyIntentional:
                continue
            }
        }

        guard !blocks.isEmpty else { return nil }

        var lines: [String] = []
        lines.append("#!/bin/bash")
        lines.append("set -euo pipefail")
        lines.append("")
        lines.append("# Generated by astrotool")
        lines.append("# Date: \(headerDateFormatter.string(from: Date()))")
        lines.append("# Root: \(root.path)")
        lines.append("#")
        lines.append("# REVIEW EVERY LINE BEFORE RUNNING.")
        lines.append("# This script was NOT executed by astrotool.")
        lines.append("")
        lines.append("read -r -p \"Type YES to continue: \" CONFIRM")
        lines.append("[ \"$CONFIRM\" = \"YES\" ] || { echo \"Aborted.\"; exit 1; }")
        lines.append("")
        for b in blocks {
            lines.append(b)
            lines.append("")
        }
        lines.append("echo \"Done. Re-run 'astrotool scan' to refresh the index.\"")

        return lines.joined(separator: "\n") + "\n"
    }

    /// Writes the generated script under
    /// `.astro_tool/suggestions/suggestions-<yyyyMMdd-HHmmss>.sh` (stamp
    /// taken from `timestamp`, not the wall clock, so callers/tests stay
    /// deterministic). Returns `nil` — and creates no file at all — when
    /// `generate` would return `nil`.
    @discardableResult
    public static func write(
        findings: [Finding],
        root: URL,
        includeSuspicious: Bool,
        timestamp: Date,
        using writeGuard: WriteGuard,
        commentSuspicious: Bool = true
    ) throws -> URL? {
        guard let content = generate(
            findings: findings,
            root: root,
            includeSuspicious: includeSuspicious,
            commentSuspicious: commentSuspicious
        ) else {
            return nil
        }

        let stamp = filenameDateFormatter.string(from: timestamp)
        let relativePath = "suggestions/suggestions-\(stamp).sh"
        return try writeGuard.writeToolFile(relativePath: relativePath, data: Data(content.utf8))
    }

    // MARK: - Per-finding block

    private static func block(for finding: Finding, root: URL, commented: Bool) -> String {
        var lines = commentLines(for: finding)
        if commented {
            lines.append("# (suspicious — uncomment only after review)")
        }

        guard let suggestion = finding.suggestion else {
            return lines.joined(separator: "\n")
        }

        switch suggestion {
        case .rename(let from, let to), .move(let from, let to):
            var mv = mvLines(from: from, to: to, root: root)
            if commented {
                mv = mv.map { "# " + $0 }
            }
            lines.append(contentsOf: mv)
        case .review(let note):
            lines.append(contentsOf: reviewLines(note: note))
        }

        return lines.joined(separator: "\n")
    }

    /// `# [<severity>] <category>: <message>` — a multi-line message keeps
    /// every extra line prefixed with `# ` on its own.
    private static func commentLines(for finding: Finding) -> [String] {
        let messageLines = finding.message.components(separatedBy: "\n")
        var lines = ["# [\(finding.severity.rawValue)] \(finding.category): \(messageLines.first ?? "")"]
        for extra in messageLines.dropFirst() {
            lines.append("# \(extra)")
        }
        return lines
    }

    /// `# REVIEW: <note>` — comment-only, never a command.
    private static func reviewLines(note: String) -> [String] {
        let noteLines = note.components(separatedBy: "\n")
        var lines = ["# REVIEW: \(noteLines.first ?? "")"]
        for extra in noteLines.dropFirst() {
            lines.append("# \(extra)")
        }
        return lines
    }

    /// A guarded `mv`: skip (never overwrite) if the destination already
    /// exists, otherwise create the destination's parent directory and move
    /// the file. Both paths are made absolute (root + relative) and
    /// single-quoted with the `'\''` shell idiom so embedded single quotes
    /// in library paths can't break the command.
    private static func mvLines(from: String, to: String, root: URL) -> [String] {
        let srcAbs = root.appendingPathComponent(from).path
        let destURL = root.appendingPathComponent(to)
        let destAbs = destURL.path
        let destParentAbs = destURL.deletingLastPathComponent().path

        return [
            "if [ -e \(shellQuote(destAbs)) ]; then",
            "  echo \"SKIP exists: \(destAbs)\"",
            "else",
            "  mkdir -p \(shellQuote(destParentAbs))",
            "  mv \(shellQuote(srcAbs)) \(shellQuote(destAbs))",
            "fi",
        ]
    }

    private static func shellQuote(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Date formatting

    /// Coarse (day-granularity) so it can't cause a spurious mismatch
    /// between two `generate` calls a few milliseconds apart, e.g. when a
    /// caller compares `write`'s output against a fresh `generate` call.
    private static let headerDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()

    private static let filenameDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyyMMdd-HHmmss"
        return formatter
    }()
}
